### PR TITLE
Align PyKML recipe with PyKML 0.2.0 package

### PR DESCRIPTION
**Pull request by jhkennedy**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

--- 
This:
* strips the `<3` python specifier as PyKML 0.2.0 supports Python 3 ( see tylere/pykml#41)
* updates the `lxml` dependency inline with PyKML's `setup.py`: https://github.com/tylere/pykml/blob/master/setup.py#L24
* uses the conda-forge recommended pip build script: https://conda-forge.org/docs/maintainer/adding_pkgs.html#use-pip

I'm working on bringing [MintPy](https://github.com/insarlab/MintPy) to conda-forge, and MintPy has historically installed the PyKML dependency via `pip` pointing directly at the PyKML GitHub repo to get Python 3 support. This PR would allow us to use the conda-forge package directly.

### CODE REVIEW

**Comment by jhkennedy** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
Thanks!

**Comment by jhkennedy** [comment]
@ocefpaf Thanks for the merge!

**Comment by ocefpaf** [comment]
BTW, if you feel like it please add yourself as a maintainer here.

**Comment by jhkennedy** [comment]
@ocefpaf sure! Will do.

**Pull request merged**
